In [1]:
import mesa
from mesa.discrete_space import FixedAgent, OrthogonalMooreGrid
import pandas as pd
import numpy as np
from scipy.stats import bernoulli
import matplotlib.pyplot as plt
import seaborn as sns
import cognitive_functions as cf

In [33]:
class individual(FixedAgent):
    """An agent that chooses between two options based on expected utility."""
    def __init__(self, model, lambd, gamma, reward_rb, reward_rf, cost_rb, min_start_wealth, p, beta, alpha, num_neighbors=20):
        """ Create a new decision maker agent.
        Args:
            self: Object that stores characteristics of the agent.
            model: Reference to the model this agent belongs to.
            num_neighbors: Number of neighbors to consider for relative desperation.
            gamma: Utility parameter.
            reward_rb: Reward for rule breaking.
            reward_rf: Reward for following rules.
            cost_rb: Cost of rule breaking.
            min_start_wealth: The  minimum starting wealth of the agent.
            p: Probability of being caught for rule-breaking.
            beta: Optimism/pessimism.
            alpha: Likelihood sensitivity.
            desperate_state: State of relative desperation (0 = not desperate, 1 = desperate).
            radius: Radius for neighborhood search.
        """
        super().__init__(model)
        self.lambd = lambd
        self.gamma = gamma
        self.reward_rb = reward_rb
        self.reward_rf = reward_rf
        self.cost_rb = cost_rb
        self.p = p
        self.beta = beta
        self.alpha = alpha

        # self.start_wealth = (np.random.pareto(a=1.7, size=1)+1) * min_start_wealth
        # self.wealth = self.start_wealth
        # self.end_wealth = self.wealth 

        self.wealth = np.random.pareto(a=1.7, size=1)[0] * min_start_wealth + 1  # Ensure wealth is above the minimum

        self.num_neighbors = num_neighbors
        self.desperate_state = 0  # Initialize desperate state to 0 (not desperate)
        self.decision = 0  # Initialize decision to 0 (follow rules)
        self.caught = False  # Initialize caught state to False
        self.income_rank = 0  # Initialize income rank to 0
        self.rb_choice = 0  # Initialize rule-breaking choice to 0 (follow rules)

    def relative_desperation(self):
        """Determine the relative desperation of the agent based on income rank."""
        # Get neighbors within the specified radius
        neighbors = self.model.grid.get_neighbors(self.pos, moore=True, include_center=False, radius=20)

        # Get a vector of the wealth of the agents in the neighborhood
        neighbor_wealths = [neighbor.wealth for neighbor in neighbors] 
        # Count the number of neighbors with wealth lower than the agent's wealth
        num_poorer_neighbors = sum(1 for w in neighbor_wealths if w <= self.wealth)

        # Calculate the income rank of the agent in its neighborhood
        income_rank = cf.income_rank(i=num_poorer_neighbors, n=len(neighbors))
        self.income_rank = income_rank  # Store the income rank in the agent's attributes

        # Label the agent as desperate if their income rank is less than 0
        if income_rank < 0:
            self.desperate_state = 1  # Agent is relatively desperate
            print(f"Agent {self.unique_id} is relatively desperate with income rank {income_rank}")
        else:
            self.desperate_state = 0  # Agent is not relatively desperate
            print(f"Agent {self.unique_id} is not relatively desperate with income rank {income_rank}")


    def compute_expected_utilities(self):
        """Choose an option based on subjective value. If agent is relatively desperate, use a different utility function."""
        if self.desperate_state == 1:
            # If the agent is relatively desperate, use a different utility function
            self.SV_rule_break = cf.SV_relative_desp_RB(
            gamma=self.gamma, starting_wealth=self.wealth, lambd=self.lambd, p=self.p, beta=self.beta, alpha=self.alpha, reward_rb=self.reward_rb, cost_rb=self.cost_rb)
        else:
            self.SV_rule_break = cf.SV_rule_break(gamma=self.gamma, reward_rb=self.reward_rb, cost_rb=self.cost_rb, p=self.p, beta=self.beta, alpha=self.alpha, starting_wealth=self.wealth)  # SV of rule breaking
        self.SV_follow_rules = cf.SV_follow_rules(reward_rf=self.reward_rf, starting_wealth=self.wealth, gamma=self.gamma) # SV of following rules
        

        # Compute the softmax probabilities
        probs = cf.softmax(self.SV_rule_break, self.SV_follow_rules)
        
        rb_choice = bernoulli.rvs(probs[0])  # Bernoulli trial for rule breaking choice
        if rb_choice==1:
            self.decision = 1 # breaks rules
            print(f"Agent {self.unique_id} chose to break the rules with probability {probs[0]}")
        else:
            self.decision = 0 # follows rules
            print(f"Agent {self.unique_id} chose to follow the rules with probability {probs[1]}")
        return rb_choice
    
    def update_wealth(self):
        """Update the agent's wealth based on the choice made."""
        self.start_wealth = self.wealth
        print(f"Agent {self.unique_id} current wealth before decision: {self.start_wealth}")
        rb_choice = self.compute_expected_utilities()  # Get the choice made by the agent
        if rb_choice==1:
            # If the agent chooses to break the rules and is NOT caught
            if bernoulli.rvs(1 - self.p) == 1:
                self.caught = False
                self.wealth += self.reward_rb
                print(f"Agent {self.unique_id} broke the rules successfully and gained {self.reward_rb}. Current wealth: {self.end_wealth}")
            # If the agent chooses to break the rules and is caught
            else:
                self.caught = True
                self.wealth -= self.cost_rb
                print(f"Agent {self.unique_id} was caught breaking the rules and lost {self.cost_rb}. Current wealth: {self.end_wealth}")
        else:
            # If the agent chooses to follow the rules
            self.wealth += self.reward_rf
        self.wealth -= 100 # Deduct the cost of living (e.g., paying for food, rent, etc.)
        self.end_wealth = self.wealth
        print(f"Agent {self.unique_id} updated wealth: {self.end_wealth}")

    
    def step(self):
        self.wealth_start = self.wealth
        self.relative_desperation() # Determine if the agent is relatively desperate
        self.compute_expected_utilities()

        # Update wealth based on decision
        if self.decision == 1: # breaks rules
            # If the agent chooses to break the rules and is NOT caught
            if bernoulli.rvs(1 - self.p) == 1:
                self.caught = False
                self.wealth += self.reward_rb
            # If the agent chooses to break the rules and is caught
            else:
                self.caught = True
                self.wealth -= self.cost_rb
        else: 
            # If the agent chooses to follow the rules
            self.wealth += self.reward_rf
        # Deduct the cost of living (e.g., paying for food, rent, etc.)
        self.wealth -= 100

        # self.update_wealth() # Update the agent's wealth based on the choice made
        self.wealth_end = self.wealth

In [34]:
def crime_proportion(model):
    agent_crimes = [agent.decision for agent in model.agents]
    n = model.width * model.height  # Total number of agents in the grid
    proportion = (sum(agent_crimes) ) / n
    return proportion

In [35]:
from mesa import Model
from mesa.datacollection import DataCollector
from mesa.space import SingleGrid
import numpy as np

# from .agents import decision_maker

class rel_DMAP_model(Model):
    """A model with a number of decision makers."""
    def __init__(self, width, height, lambd, gamma, reward_rb, reward_rf, cost_rb, min_start_wealth, p, beta, alpha, num_neighbors=20):
        super().__init__()
        # self.num_agents = N
        self.width = width
        self.height = height
        self.grid = SingleGrid(width, height, torus=True)

        self.lambd = lambd
        self.gamma = gamma
        self.reward_rb = reward_rb
        self.reward_rf = reward_rf
        self.cost_rb = cost_rb
        self.p = p
        self.beta = beta
        self.alpha = alpha

        self.num_neighbors = num_neighbors
        self.desperate_state = 0  # Initialize desperate state to 0 (not desperate)
        self.decision = 0  # Initialize decision to 0 (follow rules)
        self.caught = False  # Initialize caught state to False
        self.income_rank = 0  # Initialize income rank to 0
        self.rb_choice = 0  # Initialize rule-breaking choice to 0 (follow rules)

        # Create agents and place them on the grid
        for _, pos in self.grid.coord_iter():
            # Create a new agent at the current position
            agent = individual(
                model=self, lambd=self.lambd, gamma=self.gamma, reward_rb=self.reward_rb,
                reward_rf=self.reward_rf, cost_rb=self.cost_rb, min_start_wealth=min_start_wealth,
                p=self.p, beta=self.beta, alpha=self.alpha
            )
            # Add the agent to the grid at the current position
            self.grid.place_agent(agent, pos)

    
        self.datacollector = mesa.DataCollector(
            model_reporters={"Proportion crime": crime_proportion},
            agent_reporters={ "Wealth Start": lambda a: getattr(a, "wealth_start", a.wealth), "Wealth End": lambda a: getattr(a, "wealth_end", a.wealth), "income rank":"income_rank", "desperate_state": "desperate_state", 
                             "Rule-breaking choice": "decision", "Caught": "caught", "SV_rule_break": "SV_rule_break", "SV_follow_rules": "SV_follow_rules"}
            )
        self.running = True
        self.datacollector.collect(self)
    
    def step(self):
        # self.datacollector.collect(self)
        self.agents.do("step")
        self.datacollector.collect(self)

In [36]:
# Run the model for a number of steps
test_model = rel_DMAP_model(lambd=1, gamma=0.3, reward_rb=500, reward_rf=100, cost_rb=3000, min_start_wealth=100, p=0.1, beta=1.8, alpha=0.8, width=5, height=5)
for _ in range(50):
    test_model.step()

model_df = test_model.datacollector.get_model_vars_dataframe()
agent_df = test_model.datacollector.get_agent_vars_dataframe()

Agent 1 is not relatively desperate with income rank 0.30434782608695654
Agent 1 chose to break the rules with probability 0.9988179536829973
Agent 2 is not relatively desperate with income rank 0.391304347826087
Agent 2 chose to break the rules with probability 0.9985490458297629
Agent 3 is not relatively desperate with income rank 0.9130434782608695
Agent 3 chose to break the rules with probability 0.980747818628109
Agent 4 is not relatively desperate with income rank 0.17391304347826086
Agent 4 chose to break the rules with probability 0.9988639021937208
Agent 5 is not relatively desperate with income rank 0.5217391304347826
Agent 5 chose to break the rules with probability 0.9972046798068852
Agent 6 is not relatively desperate with income rank 0.08695652173913043
Agent 6 chose to break the rules with probability 0.9988734511687029
Agent 7 is not relatively desperate with income rank 0.21739130434782608
Agent 7 chose to break the rules with probability 0.9987100502804195
Agent 8 is not relatively desperate with income rank 0.21739130434782608
Agent 8 chose to break the rules with probability 0.9987033275046674
Agent 9 is not relatively desperate with income rank 0.5217391304347826
Agent 9 chose to break the rules with probability 0.9934829803695556
Agent 10 is not relatively desperate with income rank 0.43478260869565216
Agent 10 chose to break the rules with probability 0.9968803207895347
Agent 11 is not relatively desperate with income rank 0.391304347826087
Agent 11 chose to break the rules with probability 0.9973113723608725
Agent 12 is not relatively desperate with income rank 1.0
Agent 12 chose to break the rules with probability 0.6023713424346786
Agent 13 is not relatively desperate with income rank 0.13043478260869565
Agent 13 chose to break the rules with probability 0.9989181179981272
Agent 14 is not relatively desperate with income rank 0.5217391304347826
Agent 14 chose to break the rules with probability 0.9894067959542173
Agent 15 is not relatively desperate with income rank 0.17391304347826086
Agent 15 chose to break the rules with probability 0.9988347050098182
Agent 16 is not relatively desperate with income rank 0.43478260869565216
Agent 16 chose to break the rules with probability 0.9916713594750837
Agent 17 is not relatively desperate with income rank 0.17391304347826086
Agent 17 chose to break the rules with probability 0.9988306463098198
Agent 18 is not relatively desperate with income rank 0.13043478260869565
Agent 18 chose to break the rules with probability 0.9988704682475366
Agent 19 is not relatively desperate with income rank 0.30434782608695654
Agent 19 chose to break the rules with probability 0.9965195564186862
Agent 20 is not relatively desperate with income rank 0.21739130434782608
Agent 20 chose to break the rules with probability 0.9979420705987861
Agent 21 is not relatively desperate with income rank 0.17391304347826086
Agent 21 chose to break the rules with probability 0.9981019180002644
Agent 22 is not relatively desperate with income rank 0.13043478260869565
Agent 22 chose to break the rules with probability 0.9983262743260352
Agent 23 is not relatively desperate with income rank 0.13043478260869565
Agent 23 chose to break the rules with probability 0.9967379256633131
Agent 24 is not relatively desperate with income rank 0.08695652173913043
Agent 24 chose to break the rules with probability 0.99893272605338
Agent 25 is not relatively desperate with income rank 0.043478260869565216
Agent 25 chose to break the rules with probability 0.9989546024237487
Agent 1 is not relatively desperate with income rank 0.391304347826087
Agent 1 chose to break the rules with probability 0.981423101112579
Agent 2 is not relatively desperate with income rank 0.4782608695652174
Agent 2 chose to break the rules with probability 0.979732712837521
Agent 3 is not relatively desperate with income rank 0.9565217391304348
Agent 3 chose to break the rules with probability 0.9034899664496134
Agent 4 is not relatively desperate with income rank 0.2608695652173913
Agent 4 chose to break the rules with probability 0.9817196287136787
Agent 5 is not relatively desperate with income rank 0.6086956521739131
Agent 5 chose to break the rules with probability 0.9720646396182003
Agent 6 is not relatively desperate with income rank 0.17391304347826086
Agent 6 chose to break the rules with probability 0.9817815634201942
Agent 7 is not relatively desperate with income rank 0.30434782608695654
Agent 7 chose to break the rules with probability 0.9807359957338254
Agent 8 is not relatively desperate with income rank 0.30434782608695654
Agent 8 chose to break the rules with probability 0.9806935950885752
Agent 9 is relatively desperate with income rank -0.043478260869565216
Agent 9 chose to follow the rules with probability 1.0
Agent 10 is not relatively desperate with income rank 0.5217391304347826
Agent 10 chose to break the rules with probability 0.9703469110858659
Agent 11 is not relatively desperate with income rank 0.4782608695652174
Agent 11 chose to break the rules with probability 0.9726386259960511
Agent 12 is not relatively desperate with income rank 0.043478260869565216
Agent 12 chose to break the rules with probability 0.999999999444759
Agent 13 is not relatively desperate with income rank 0.17391304347826086
Agent 13 chose to break the rules with probability 0.9820727391324363
Agent 14 is not relatively desperate with income rank 0.5652173913043478
Agent 14 chose to break the rules with probability 0.9365700960087836
Agent 15 is not relatively desperate with income rank 0.2608695652173913
Agent 15 chose to break the rules with probability 0.981530922260114
Agent 16 is not relatively desperate with income rank 0.5217391304347826
Agent 16 chose to break the rules with probability 0.9460387187777828
Agent 17 is not relatively desperate with income rank 0.2608695652173913
Agent 17 chose to break the rules with probability 0.981504768632013
Agent 18 is not relatively desperate with income rank 0.21739130434782608
Agent 18 chose to break the rules with probability 0.9817622045007239
Agent 19 is not relatively desperate with income rank 0.391304347826087
Agent 19 chose to break the rules with probability 0.9684795837450725
Agent 20 is not relatively desperate with income rank 0.30434782608695654
Agent 20 chose to break the rules with probability 0.976139147851449
Agent 21 is not relatively desperate with income rank 0.2608695652173913
Agent 21 chose to break the rules with probability 0.9770605924022064
Agent 22 is not relatively desperate with income rank 0.2608695652173913
Agent 22 chose to break the rules with probability 0.9783823944906156
Agent 23 is not relatively desperate with income rank 0.2608695652173913
Agent 23 chose to break the rules with probability 0.9696047688554561
Agent 24 is not relatively desperate with income rank 0.2608695652173913
Agent 24 chose to break the rules with probability 0.9821685030468055
Agent 25 is not relatively desperate with income rank 0.21739130434782608
Agent 25 chose to break the rules with probability 0.982312422858795
Agent 1 is not relatively desperate with income rank 0.5652173913043478
Agent 1 chose to follow the rules with probability 0.09406481167344795
Agent 2 is not relatively desperate with income rank 0.6521739130434783
Agent 2 chose to break the rules with probability 0.8998490370847378
Agent 3 is not relatively desperate with income rank 0.9565217391304348
Agent 3 chose to break the rules with probability 0.6896252101723686
Agent 4 is not relatively desperate with income rank 0.43478260869565216
Agent 4 chose to follow the rules with probability 0.09298502132172291
Agent 5 is not relatively desperate with income rank 0.782608695652174
Agent 5 chose to break the rules with probability 0.8735191857853253
Agent 6 is not relatively desperate with income rank 0.34782608695652173
Agent 6 chose to break the rules with probability 0.9072409860393971
Agent 7 is not relatively desperate with income rank 0.5652173913043478
Agent 7 chose to break the rules with probability 0.903447322982557
Agent 8 is not relatively desperate with income rank 0.043478260869565216
Agent 8 chose to break the rules with probability 0.9999999999179505
Agent 9 is relatively desperate with income rank -0.043478260869565216
Agent 9 chose to follow the rules with probability 1.0
Agent 10 is not relatively desperate with income rank 0.6956521739130435
Agent 10 chose to break the rules with probability 0.8678686346808218
Agent 11 is not relatively desperate with income rank 0.6521739130434783
Agent 11 chose to break the rules with probability 0.8754258586337287
Agent 12 is not relatively desperate with income rank 0.21739130434782608
Agent 12 chose to break the rules with probability 0.9999999984540733
Agent 13 is not relatively desperate with income rank 0.30434782608695654
Agent 13 chose to follow the rules with probability 0.09169425017270609
Agent 14 is not relatively desperate with income rank 0.13043478260869565
Agent 14 chose to break the rules with probability 0.9999999998583393
Agent 15 is not relatively desperate with income rank 0.43478260869565216
Agent 15 chose to follow the rules with probability 0.09367261990527727
Agent 16 is not relatively desperate with income rank 0.6956521739130435
Agent 16 chose to break the rules with probability 0.7950512934380515
Agent 17 is not relatively desperate with income rank 0.4782608695652174
Agent 17 chose to break the rules with probability 0.9062322028004762
Agent 18 is not relatively desperate with income rank 0.34782608695652173
Agent 18 chose to break the rules with probability 0.9071703252066249
Agent 19 is not relatively desperate with income rank 0.5652173913043478
Agent 19 chose to break the rules with probability 0.8618162240546288
Agent 20 is not relatively desperate with income rank 0.5217391304347826
Agent 20 chose to break the rules with probability 0.8872684279280522
Agent 21 is not relatively desperate with income rank 0.043478260869565216
Agent 21 chose to break the rules with probability 0.999999999912071
Agent 22 is not relatively desperate with income rank 0.4782608695652174
Agent 22 chose to break the rules with probability 0.8950673588400297
Agent 23 is not relatively desperate with income rank 0.08695652173913043
Agent 23 chose to break the rules with probability 0.9999999999008777
Agent 24 is not relatively desperate with income rank 0.2608695652173913
Agent 24 chose to break the rules with probability 0.9086567465696627
Agent 25 is not relatively desperate with income rank 0.043478260869565216
Agent 25 chose to break the rules with probability 0.9999999999206906
Agent 1 is not relatively desperate with income rank 0.43478260869565216
Agent 1 chose to break the rules with probability 0.9059351883265521
Agent 2 is not relatively desperate with income rank 0.6521739130434783
Agent 2 chose to follow the rules with probability 0.31843031879779815
Agent 3 is not relatively desperate with income rank 1.0
Agent 3 chose to follow the rules with probability 0.638851654644568
Agent 4 is not relatively desperate with income rank 0.34782608695652173
Agent 4 chose to break the rules with probability 0.907014978678277
Agent 5 is not relatively desperate with income rank 0.8260869565217391
Agent 5 chose to follow the rules with probability 0.37306413293069235
Agent 6 is not relatively desperate with income rank 0.391304347826087
Agent 6 chose to break the rules with probability 0.6980638095849157
Agent 7 is not relatively desperate with income rank 0.5652173913043478
Agent 7 chose to break the rules with probability 0.6895300984196036
Agent 8 is not relatively desperate with income rank 0.13043478260869565
Agent 8 chose to break the rules with probability 0.999999999820256
Agent 9 is not relatively desperate with income rank 0.0
Agent 9 chose to break the rules with probability 0.9999999999431908
Agent 10 is not relatively desperate with income rank 0.782608695652174
Agent 10 chose to break the rules with probability 0.6159671293433097
Agent 11 is not relatively desperate with income rank 0.6956521739130435
Agent 11 chose to break the rules with probability 0.6306937266368363
Agent 12 is not relatively desperate with income rank 0.2608695652173913
Agent 12 chose to break the rules with probability 0.9999999947636882
Agent 13 is not relatively desperate with income rank 0.30434782608695654
Agent 13 chose to break the rules with probability 0.9083057498272938
Agent 14 is not relatively desperate with income rank 0.17391304347826086
Agent 14 chose to break the rules with probability 0.9999999996714486
Agent 15 is not relatively desperate with income rank 0.30434782608695654
Agent 15 chose to break the rules with probability 0.9063273800947227
Agent 16 is not relatively desperate with income rank 0.782608695652174
Agent 16 chose to follow the rules with probability 0.5064219207782397
Agent 17 is not relatively desperate with income rank 0.4782608695652174
Agent 17 chose to follow the rules with probability 0.30421981205384924
Agent 18 is not relatively desperate with income rank 0.34782608695652173
Agent 18 chose to break the rules with probability 0.6979035083651219
Agent 19 is not relatively desperate with income rank 0.7391304347826086
Agent 19 chose to break the rules with probability 0.6044881015809018
Agent 20 is not relatively desperate with income rank 0.6521739130434783
Agent 20 chose to break the rules with probability 0.6547056311953708
Agent 21 is relatively desperate with income rank -0.043478260869565216
Agent 21 chose to follow the rules with probability 1.0
Agent 22 is not relatively desperate with income rank 0.6086956521739131
Agent 22 chose to follow the rules with probability 0.3288141026416649
Agent 23 is not relatively desperate with income rank 0.13043478260869565
Agent 23 chose to break the rules with probability 0.9999999997787037
Agent 24 is not relatively desperate with income rank 0.08695652173913043
Agent 24 chose to break the rules with probability 0.9999999998262419
Agent 25 is not relatively desperate with income rank 0.043478260869565216
Agent 25 chose to break the rules with probability 0.9999999998268339
Agent 1 is not relatively desperate with income rank 0.5217391304347826
Agent 1 chose to break the rules with probability 0.6951098274415456
Agent 2 is not relatively desperate with income rank 0.5217391304347826
Agent 2 chose to break the rules with probability 0.681569681202202
Agent 3 is not relatively desperate with income rank 0.7391304347826086
Agent 3 chose to follow the rules with probability 0.638851654644568
Agent 4 is not relatively desperate with income rank 0.391304347826087
Agent 4 chose to break the rules with probability 0.6975512715052666
Agent 5 is not relatively desperate with income rank 0.5217391304347826
Agent 5 chose to follow the rules with probability 0.37306413293069235
Agent 6 is not relatively desperate with income rank 0.6086956521739131
Agent 6 chose to follow the rules with probability 0.6297066919942647
Agent 7 is not relatively desperate with income rank 0.782608695652174
Agent 7 chose to break the rules with probability 0.3610464976641254
Agent 8 is not relatively desperate with income rank 0.17391304347826086
Agent 8 chose to break the rules with probability 0.9999999995715876
Agent 9 is not relatively desperate with income rank 0.0
Agent 9 chose to break the rules with probability 0.9999999998797855
Agent 10 is not relatively desperate with income rank 0.9130434782608695
Agent 10 chose to break the rules with probability 0.289603666062696
Agent 11 is not relatively desperate with income rank 0.8695652173913043
Agent 11 chose to follow the rules with probability 0.6971776332590964
Agent 12 is not relatively desperate with income rank 0.30434782608695654
Agent 12 chose to break the rules with probability 0.9999999747710127
Agent 13 is not relatively desperate with income rank 0.34782608695652173
Agent 13 chose to break the rules with probability 0.7004856387083813
Agent 14 is not relatively desperate with income rank 0.21739130434782608
Agent 14 chose to break the rules with probability 0.9999999991541697
Agent 15 is not relatively desperate with income rank 0.34782608695652173
Agent 15 chose to break the rules with probability 0.6959951949432761
Agent 16 is not relatively desperate with income rank 0.4782608695652174
Agent 16 chose to follow the rules with probability 0.5064219207782397
Agent 17 is not relatively desperate with income rank 0.34782608695652173
Agent 17 chose to follow the rules with probability 0.30421981205384924
Agent 18 is not relatively desperate with income rank 0.13043478260869565
Agent 18 chose to break the rules with probability 0.9999999995830864
Agent 19 is not relatively desperate with income rank 0.9130434782608695
Agent 19 chose to follow the rules with probability 0.7203632552785167
Agent 20 is not relatively desperate with income rank 0.8260869565217391
Agent 20 chose to break the rules with probability 0.3254853277757712
Agent 21 is relatively desperate with income rank -0.043478260869565216
Agent 21 chose to follow the rules with probability 1.0
Agent 22 is not relatively desperate with income rank 0.391304347826087
Agent 22 chose to break the rules with probability 0.6711858973583351
Agent 23 is not relatively desperate with income rank 0.13043478260869565
Agent 23 chose to break the rules with probability 0.9999999994590838
Agent 24 is not relatively desperate with income rank 0.08695652173913043
Agent 24 chose to break the rules with probability 0.9999999995875004
Agent 25 is not relatively desperate with income rank 0.043478260869565216
Agent 25 chose to break the rules with probability 0.9999999995890698
Agent 1 is not relatively desperate with income rank 0.6521739130434783
Agent 1 chose to follow the rules with probability 0.632932596976842
Agent 2 is not relatively desperate with income rank 0.7391304347826086
Agent 2 chose to follow the rules with probability 0.6473830867931026
Agent 3 is not relatively desperate with income rank 0.6956521739130435
Agent 3 chose to follow the rules with probability 0.638851654644568
Agent 4 is not relatively desperate with income rank 0.5652173913043478
Agent 4 chose to follow the rules with probability 0.6302683365973433
Agent 5 is not relatively desperate with income rank 0.391304347826087
Agent 5 chose to break the rules with probability 0.6269358670693076
Agent 6 is not relatively desperate with income rank 0.4782608695652174
Agent 6 chose to follow the rules with probability 0.6297066919942647
Agent 7 is not relatively desperate with income rank 0.9130434782608695
Agent 7 chose to follow the rules with probability 0.8796412679360924
Agent 8 is not relatively desperate with income rank 0.17391304347826086
Agent 8 chose to break the rules with probability 0.9999999988542128
Agent 9 is not relatively desperate with income rank 0.0
Agent 9 chose to break the rules with probability 0.9999999997261397
Agent 10 is not relatively desperate with income rank 1.0
Agent 10 chose to follow the rules with probability 0.9126883021973623
Agent 11 is not relatively desperate with income rank 0.782608695652174
Agent 11 chose to follow the rules with probability 0.6971776332590964
Agent 12 is not relatively desperate with income rank 0.30434782608695654
Agent 12 chose to break the rules with probability 0.99999953144275
Agent 13 is not relatively desperate with income rank 0.43478260869565216
Agent 13 chose to follow the rules with probability 0.6270418045714464
Agent 14 is not relatively desperate with income rank 0.21739130434782608
Agent 14 chose to break the rules with probability 0.9999999974678551
Agent 15 is not relatively desperate with income rank 0.5652173913043478
Agent 15 chose to break the rules with probability 0.3680314587297168
Agent 16 is not relatively desperate with income rank 0.43478260869565216
Agent 16 chose to break the rules with probability 0.4935780792217604

In [37]:
agent_df.head(51)

              Wealth Start   Wealth End  income rank  desperate_state  \
Step AgentID
0    1           15.120797    15.120797     0.000000                0
     2           33.388709    33.388709     0.000000                0
     3          422.568258   422.568258     0.000000                0
     4           11.783694    11.783694     0.000000                0
     5          103.715918   103.715918     0.000000                0
     6           11.081372    11.081372     0.000000                0
     7           22.696821    22.696821     0.000000                0
     8           23.157383    23.157383     0.000000                0
     9          222.652111   222.652111     0.000000                0
     10         117.320882   117.320882     0.000000                0
     11          99.021507    99.021507     0.000000                0
     12        1334.001305  1334.001305     0.000000                0
     13           7.754413     7.754413     0.000000                0
     14         305.657154   305.657154     0.000000                0
     15          13.912215    13.912215     0.000000                0
     16         263.210171   263.210171     0.000000                0
     17          14.205879    14.205879     0.000000                0
     18          11.301096    11.301096     0.000000                0
     19         131.416571   131.416571     0.000000                0
     20          68.568608    68.568608     0.000000                0
     21          59.968266    59.968266     0.000000                0
     22          47.143120    47.143120     0.000000                0
     23         123.005447   123.005447     0.000000                0
     24           6.651039     6.651039     0.000000                0
     25           4.984132     4.984132     0.000000                0
1    1           15.120797   415.120797     0.304348                0
     2           33.388709   433.388709     0.391304                0
     3          422.568258   822.568258     0.913043                0
     4           11.783694   411.783694     0.173913                0
     5          103.715918   503.715918     0.521739                0
     6           11.081372   411.081372     0.086957                0
     7           22.696821   422.696821     0.217391                0
     8           23.157383   423.157383     0.217391                0
     9          222.652111 -2877.347889     0.521739                0
     10         117.320882   517.320882     0.434783                0
     11          99.021507   499.021507     0.391304                0
     12        1334.001305 -1765.998695     1.000000                0
     13           7.754413   407.754413     0.130435                0
     14         305.657154   705.657154     0.521739                0
     15          13.912215   413.912215     0.173913                0
     16         263.210171   663.210171     0.434783                0
     17          14.205879   414.205879     0.173913                0
     18          11.301096   411.301096     0.130435                0
     19         131.416571   531.416571     0.304348                0
     20          68.568608   468.568608     0.217391                0
     21          59.968266   459.968266     0.173913                0
     22          47.143120   447.143120     0.130435                0
     23         123.005447   523.005447     0.130435                0
     24           6.651039   406.651039     0.086957                0
     25           4.984132   404.984132     0.043478                0
2    1          415.120797   815.120797     0.391304                0

              Rule-breaking choice  Caught  SV_rule_break  SV_follow_rules
Step AgentID
0    1                           0   False            NaN              NaN
     2                           0   False            NaN              NaN
     3                           0   False            NaN              NaN
     4                           0   False            NaN              NaN
     5                           0   False            NaN              NaN
     6                           0   False            NaN              NaN
     7                           0   False            NaN              NaN
     8                           0   False            NaN              NaN
     9                           0   False            NaN              NaN
     10                          0   False            NaN              NaN
     11                          0   False            NaN              NaN
     12                          0   False            NaN              NaN
     13                          0   False            NaN              NaN
     14                          0   False            NaN              NaN
     15                          0   False            NaN              NaN
     16                          0   False            NaN              NaN
     17                          0   False            NaN              NaN
     18                          0   False            NaN              NaN
     19                          0   False            NaN              NaN
     20                          0   False            NaN              NaN
     21                          0   False            NaN              NaN
     22                          0   False            NaN              NaN
     23                          0   False            NaN              NaN
     24                          0   False            NaN              NaN
     25                          0   False            NaN              NaN
1    1                           1   False      10.892174         4.152849
     2                           1   False      10.874542         4.340460
     3                           1   False      10.468661         6.537970
     4                           1   False      10.895381         4.116362
     5                           1   False      10.805427         4.928417
     6                           1   False      10.896055         4.108586
     7                           1   False      10.884878         4.233017
     8                           1   False      10.884434         4.237777
     9                           1    True      10.684245         5.657445
     10                          1   False      10.791835         5.024935
     11                          1   False      10.810100         4.894068
     12                          1    True       9.265796         8.850440
     13                          1   False      10.899246         4.071276
     14                          1   False      10.596546         6.059653
     15                          1   False      10.893336         4.139721
     16                          1   False      10.641713         5.862021
     17                          1   False      10.893054         4.142920
     18                          1   False      10.895844         4.111022
     19                          1   False      10.777679         5.120570
     20                          1   False      10.840210         4.656215
     21                          1   False      10.848648         4.583636
     22                          1   False      10.861177         4.470149
     23                          1   False      10.786136         5.064011
     24                          1   False      10.900304         4.058724
     25                          1   False      10.901900         4.039588
2    1                           1   False      10.476961         6.509876

In [31]:
# (ambiguity aversion)/beta mean: 0.12; median: 0.09, SD: 0.41, min: -0.97 max: 0.97
# (a-insensitivity)/alpha mean: 0.41 median: 0.29, SD: 0.44 min: -0.22 max: 2.2
parameters = {"gamma": 0.3,
              "reward_rb": [500, 1000],
              "reward_rf": [50, 100],
              "cost_rb": [500, 1000],
              "min_start_wealth": [200,1000],
              "p": 0.1,
              "beta": [-0.97, 0.97],
              "alpha": [-0.22, 2.2],
              "lambd": 1,  # Add lambda parameter
              "width": 5,  # Add width parameter
              "height": 5}  # Add height parameter
results = mesa.batch_run(
    rel_DMAP_model,
    parameters,
    iterations=1,
    max_steps=10,
    data_collection_period=1,
    number_processes=1  # Change to use multiple CPU cores for parallel execution
)

  0%|          | 0/64 [00:00<?, ?it/s]

Agent 1 is not relatively desperate with income rank 0.391304347826087
Agent 1 chose to break the rules with probability [0.98883087]
Agent 2 is not relatively desperate with income rank 0.5652173913043478
Agent 2 chose to break the rules with probability [0.99472419]
Agent 3 is not relatively desperate with income rank 0.043478260869565216
Agent 3 chose to break the rules with probability [0.98219912]
Agent 4 is not relatively desperate with income rank 0.13043478260869565
Agent 4 chose to break the rules with probability [0.98601926]
Agent 5 is not relatively desperate with income rank 0.2608695652173913
Agent 5 chose to break the rules with probability [0.98834778]
Agent 6 is not relatively desperate with income rank 0.43478260869565216
Agent 6 chose to break the rules with probability [0.99649271]
Agent 7 is not relatively desperate with income rank 0.9130434782608695
Agent 7 chose to break the rules with probability [1.]
Agent 8 is not relatively desperate with income rank 0.17391304347826086
Agent 8 chose to break the rules with probability [0.98657168]
Agent 9 is relatively desperate with income rank -0.043478260869565216
Agent 9 chose to follow the rules with probability [1.]
Agent 10 is not relatively desperate with income rank 0.34782608695652173
Agent 10 chose to break the rules with probability [0.99348389]
Agent 11 is not relatively desperate with income rank 0.2608695652173913
Agent 11 chose to break the rules with probability [0.99208806]
Agent 12 is not relatively desperate with income rank 0.8695652173913043
Agent 12 chose to break the rules with probability [1.]
Agent 13 is not relatively desperate with income rank 0.6086956521739131
Agent 13 chose to break the rules with probability [0.99999998]
Agent 14 is not relatively desperate with income rank 1.0
Agent 14 chose to break the rules with probability [1.]
Agent 15 is not relatively desperate with income rank 0.9565217391304348
Agent 15 chose to break the rules with probability [1.]
Agent 16 is not relatively desperate with income rank 0.043478260869565216
Agent 16 chose to break the rules with probability [0.98506324]
Agent 17 is not relatively desperate with income rank 0.17391304347826086
Agent 17 chose to break the rules with probability [0.98660484]
Agent 18 is not relatively desperate with income rank 0.30434782608695654
Agent 18 chose to break the rules with probability [0.99794351]
Agent 19 is not relatively desperate with income rank 0.08695652173913043
Agent 19 chose to break the rules with probability [0.98219603]
Agent 20 is not relatively desperate with income rank 0.7391304347826086
Agent 20 chose to break the rules with probability [0.99999999]
Agent 21 is not relatively desperate with income rank 0.17391304347826086
Agent 21 chose to break the rules with probability [0.99080815]
Agent 22 is not relatively desperate with income rank 0.08695652173913043
Agent 22 chose to break the rules with probability [0.98554823]
Agent 23 is not relatively desperate with income rank 0.13043478260869565
Agent 23 chose to break the rules with probability [0.98610341]
Agent 24 is not relatively desperate with income rank 0.17391304347826086
Agent 24 chose to break the rules with probability [0.99999986]
Agent 25 is not relatively desperate with income rank 0.13043478260869565
Agent 25 chose to break the rules with probability [0.99289604]
Agent 1 is not relatively desperate with income rank 0.391304347826087
Agent 1 chose to break the rules with probability [0.99999997]
Agent 2 is not relatively desperate with income rank 0.5652173913043478
Agent 2 chose to break the rules with probability [0.99999999]
Agent 3 is not relatively desperate with income rank 0.17391304347826086
Agent 3 chose to break the rules with probability [0.99999993]
Agent 4 is not relatively desperate with income rank 0.17391304347826086
Agent 4 chose to break the rules with probability [0.99999996]
Agent 5 is not relatively desperate with income rank 0.2608695652173913
Agent 5 chose to break the rules with probability [0.99999997]
Agent 6 is not relatively desperate with income rank 0.43478260869565216
Agent 6 chose to break the rules with probability [0.99999999]
Agent 7 is not relatively desperate with income rank 0.9130434782608695
Agent 7 chose to break the rules with probability [1.]
Agent 8 is not relatively desperate with income rank 0.21739130434782608
Agent 8 chose to break the rules with probability [0.99999996]
Agent 9 is not relatively desperate with income rank 0.08695652173913043
Agent 9 chose to break the rules with probability [0.97267374]
Agent 10 is not relatively desperate with income rank 0.34782608695652173
Agent 10 chose to break the rules with probability [0.99999998]
Agent 11 is not relatively desperate with income rank 0.2608695652173913
Agent 11 chose to break the rules with probability [0.99999998]
Agent 12 is not relatively desperate with income rank 0.8695652173913043
Agent 12 chose to break the rules with probability [1.]
Agent 13 is not relatively desperate with income rank 0.6086956521739131
Agent 13 chose to break the rules with probability [1.]
Agent 14 is not relatively desperate with income rank 1.0
Agent 14 chose to break the rules with probability [1.]
Agent 15 is not relatively desperate with income rank 0.9565217391304348
Agent 15 chose to break the rules with probability [1.]
Agent 16 is not relatively desperate with income rank 0.0
Agent 16 chose to break the rules with probability [0.99751858]
Agent 17 is not relatively desperate with income rank 0.043478260869565216
Agent 17 chose to break the rules with probability [0.99804092]
Agent 18 is not relatively desperate with income rank 0.30434782608695654
Agent 18 chose to break the rules with probability [0.99999999]
Agent 19 is not relatively desperate with income rank 0.13043478260869565
Agent 19 chose to break the rules with probability [0.99999993]
Agent 20 is not relatively desperate with income rank 0.7391304347826086
Agent 20 chose to break the rules with probability [1.]
Agent 21 is not relatively desperate with income rank 0.17391304347826086
Agent 21 chose to break the rules with probability [0.99999998]
Agent 22 is not relatively desperate with income rank 0.0
Agent 22 chose to break the rules with probability [0.997697]
Agent 23 is not relatively desperate with income rank 0.13043478260869565
Agent 23 chose to break the rules with probability [0.99999996]
Agent 24 is not relatively desperate with income rank 0.17391304347826086
Agent 24 chose to break the rules with probability [1.]
Agent 25 is not relatively desperate with income rank 0.13043478260869565
Agent 25 chose to break the rules with probability [0.99999998]
Agent 1 is not relatively desperate with income rank 0.391304347826087
Agent 1 chose to break the rules with probability [1.]
Agent 2 is not relatively desperate with income rank 0.5652173913043478
Agent 2 chose to break the rules with probability [1.]
Agent 3 is not relatively desperate with income rank 0.17391304347826086
Agent 3 chose to break the rules with probability [1.]
Agent 4 is not relatively desperate with income rank 0.17391304347826086
Agent 4 chose to break the rules with probability [1.]
Agent 5 is not relatively desperate with income rank 0.2608695652173913
Agent 5 chose to break the rules with probability [1.]
Agent 6 is not relatively desperate with income rank 0.43478260869565216
Agent 6 chose to break the rules with probability [1.]
Agent 7 is not relatively desperate with income rank 0.9130434782608695
Agent 7 chose to break the rules with probability [1.]
Agent 8 is not relatively desperate with income rank 0.21739130434782608
Agent 8 chose to break the rules with probability [1.]
Agent 9 is relatively desperate with income rank -0.043478260869565216
Agent 9 chose to break the rules with probability [1.]
Agent 10 is not relatively desperate with income rank 0.391304347826087
Agent 10 chose to break the rules with probability [1.]
Agent 11 is not relatively desperate with income rank 0.30434782608695654
Agent 11 chose to break the rules with probability [1.]
Agent 12 is not relatively desperate with income rank 0.8695652173913043
Agent 12 chose to break the rules with probability [1.]
Agent 13 is not relatively desperate with income rank 0.6086956521739131
Agent 13 chose to break the rules with probability [1.]
Agent 14 is not relatively desperate with income rank 1.0
Agent 14 chose to break the rules with probability [1.]
Agent 15 is not relatively desperate with income rank 0.9565217391304348
Agent 15 chose to break the rules with probability [1.]
Agent 16 is not relatively desperate with income rank 0.0
Agent 16 chose to break the rules with probability [0.95810792]
Agent 17 is not relatively desperate with income rank 0.043478260869565216
Agent 17 chose to break the rules with probability [0.95854884]
Agent 18 is not relatively desperate with income rank 0.34782608695652173
Agent 18 chose to break the rules with probability [1.]
Agent 19 is not relatively desperate with income rank 0.17391304347826086
Agent 19 chose to break the rules with probability [1.]
Agent 20 is not relatively desperate with income rank 0.7391304347826086
Agent 20 chose to break the rules with probability [1.]
Agent 21 is not relatively desperate with income rank 0.21739130434782608
Agent 21 chose to break the rules with probability [1.]
Agent 22 is not relatively desperate with income rank 0.0
Agent 22 chose to break the rules with probability [0.9581807]
Agent 23 is not relatively desperate with income rank 0.17391304347826086
Agent 23 chose to break the rules with probability [1.]
Agent 24 is not relatively desperate with income rank 0.21739130434782608
Agent 24 chose to break the rules with probability [1.]
Agent 25 is not relatively desperate with income rank 0.17391304347826086
Agent 25 chose to break the rules with probability [1.]
Agent 1 is not relatively desperate with income rank 0.391304347826087
Agent 1 chose to break the rules with probability [1.]
Agent 2 is not relatively desperate with income rank 0.6086956521739131
Agent 2 chose to break the rules with probability [1.]
Agent 3 is not relatively desperate with income rank 0.30434782608695654
Agent 3 chose to break the rules with probability [1.]
Agent 4 is not relatively desperate with income rank 0.30434782608695654
Agent 4 chose to break the rules with probability [1.]
Agent 5 is not relatively desperate with income rank 0.34782608695652173
Agent 5 chose to break the rules with probability [1.]
Agent 6 is not relatively desperate with income rank 0.5217391304347826
Agent 6 chose to break the rules with probability [1.]
Agent 7 is not relatively desperate with income rank 0.9130434782608695
Agent 7 chose to break the rules with probability [1.]
Agent 8 is not relatively desperate with income rank 0.08695652173913043
Agent 8 chose to break the rules with probability [0.99916086]
Agent 9 is relatively desperate with income rank -0.043478260869565216
Agent 9 chose to follow the rules with probability [1.]
Agent 10 is not relatively desperate with income rank 0.4782608695652174
Agent 10 chose to break the rules with probability [1.]
Agent 11 is not relatively desperate with income rank 0.391304347826087
Agent 11 chose to break the rules with probability [1.]
Agent 12 is not relatively desperate with income rank 0.8695652173913043
Agent 12 chose to break the rules with probability [1.]
Agent 13 is not relatively desperate with income rank 0.6521739130434783
Agent 13 chose to break the rules with probability [1.]
Agent 14 is not relatively desperate with income rank 1.0
Agent 14 chose to break the rules with probability [1.]
Agent 15 is not relatively desperate with income rank 0.9565217391304348
Agent 15 chose to break the rules with probability [1.]
Agent 16 is not relatively desperate with income rank 0.0
Agent 16 chose to break the rules with probability [0.99886724]
Agent 17 is not relatively desperate with income rank 0.043478260869565216
Agent 17 chose to break the rules with probability [0.99916702]
Agent 18 is not relatively desperate with income rank 0.43478260869565216
Agent 18 chose to break the rules with probability [1.]
Agent 19 is not relatively desperate with income rank 0.30434782608695654
Agent 19 chose to break the rules with probability [1.]
Agent 20 is not relatively desperate with income rank 0.782608695652174
Agent 20 chose to break the rules with probability [1.]
Agent 21 is not relatively desperate with income rank 0.34782608695652173
Agent 21 chose to break the rules with probability [1.]
Agent 22 is not relatively desperate with income rank 0.0
Agent 22 chose to break the rules with probability [0.99896446]
Agent 23 is not relatively desperate with income rank 0.30434782608695654
Agent 23 chose to break the rules with probability [1.]
Agent 24 is not relatively desperate with income rank 0.34782608695652173
Agent 24 chose to break the rules with probability [1.]
Agent 25 is not relatively desperate with income rank 0.30434782608695654
Agent 25 chose to break the rules with probability [1.]
Agent 1 is not relatively desperate with income rank 0.17391304347826086
Agent 1 chose to break the rules with probability [1.]
Agent 2 is not relatively desperate with income rank 0.17391304347826086
Agent 2 chose to break the rules with probability [1.]
Agent 3 is not relatively desperate with income rank 0.34782608695652173
Agent 3 chose to break the rules with probability [1.]
Agent 4 is not relatively desperate with income rank 0.34782608695652173
Agent 4 chose to break the rules with probability [1.]
Agent 5 is not relatively desperate with income rank 0.391304347826087
Agent 5 chose to break the rules with probability [1.]
Agent 6 is not relatively desperate with income rank 0.5652173913043478
Agent 6 chose to break the rules with probability [1.]
Agent 7 is not relatively desperate with income rank 0.9130434782608695
Agent 7 chose to break the rules with probability [1.]
Agent 8 is not relatively desperate with income rank 0.13043478260869565
Agent 8 chose to break the rules with probability [0.99999999]
Agent 9 is relatively desperate with income rank -0.043478260869565216
Agent 9 chose to follow the rules with probability [1.]
Agent 10 is not relatively desperate with income rank 0.5217391304347826
Agent 10 chose to break the rules with probability [1.]
Agent 11 is not relatively desperate with income rank 0.43478260869565216
Agent 11 chose to break the rules with probability [1.]
Agent 12 is not relatively desperate with income rank 0.8695652173913043
Agent 12 chose to break the rules with probability [1.]
Agent 13 is not relatively desperate with income rank 0.6521739130434783
Agent 13 chose to break the rules with probability [1.]
Agent 14 is not relatively desperate with income rank 1.0
Agent 14 chose to break the rules with probability [1.]
Agent 15 is not relatively desperate with income rank 0.9565217391304348
Agent 15 chose to break the rules with probability [1.]
Agent 16 is not relatively desperate with income rank 0.043478260869565216
Agent 16 chose to break the rules with probability [0.99999999]
Agent 17 is not relatively desperate with income rank 0.08695652173913043
Agent 17 chose to break the rules with probability [0.99999999]
Agent 18 is not relatively desperate with income rank 0.08695652173913043
Agent 18 chose to break the rules with probability [1.]
Agent 19 is not relatively desperate with income rank 0.30434782608695654
Agent 19 chose to break the rules with probability [1.]
Agent 20 is not relatively desperate with income rank 0.782608695652174
Agent 20 chose to break the rules with probability [1.]
Agent 21 is not relatively desperate with income rank 0.34782608695652173
Agent 21 chose to break the rules with probability [1.]
Agent 22 is not relatively desperate with income rank 0.08695652173913043
Agent 22 chose to break the rules with probability [0.99999999]
Agent 23 is not relatively desperate with income rank 0.30434782608695654
Agent 23 chose to break the rules with probability [1.]
Agent 24 is not relatively desperate with income rank 0.34782608695652173
Agent 24 chose to break the rules with probability [1.]
Agent 25 is not relatively desperate with income rank 0.34782608695652173
Agent 25 chose to break the rules with probability [1.]
Agent 1 is not relatively desperate with income rank 0.2608695652173913
Agent 1 chose to break the rules with probability [1.]
Agent 2 is not relatively desperate with income rank 0.0
Agent 2 chose to break the rules with probability [0.99472419]
Agent 3 is not relatively desperate with income rank 0.43478260869565216
Agent 3 chose to break the rules with probability [1.]
Agent 4 is not relatively desperate with income rank 0.43478260869565216
Agent 4 chose to break the rules with probability [1.]
Agent 5 is not relatively desperate with income rank 0.4782608695652174
Agent 5 chose to break the rules with probability [1.]
Agent 6 is not relatively desperate with income rank 0.6521739130434783
Agent 6 chose to break the rules with probability [1.]
Agent 7 is not relatively desperate with income rank 0.9130434782608695
Agent 7 chose to break the rules with probability [1.]
Agent 8 is not relatively desperate with income rank 0.21739130434782608
Agent 8 chose to break the rules with probability [1.]
Agent 9 is relatively desperate with income rank -0.043478260869565216
Agent 9 chose to break the rules with probability [0.99999997]
Agent 10 is not relatively desperate with income rank 0.6086956521739131
Agent 10 chose to break the rules with probability [1.]
Agent 11 is not relatively desperate with income rank 0.5652173913043478
Agent 11 chose to break the rules with probability [1.]
Agent 12 is not relatively desperate with income rank 0.8695652173913043
Agent 12 chose to break the rules with probability [1.]
Agent 13 is not relatively desperate with income rank 0.6521739130434783
Agent 13 chose to break the rules with probability [1.]
Agent 14 is not relatively desperate with income rank 1.0
Agent 14 chose to break the rules with probability [1.]
Agent 15 is not relatively desperate with income rank 0.9565217391304348
Agent 15 chose to break the rules with probability [1.]
Agent 16 is not relatively desperate with income rank 0.13043478260869565
Agent 16 chose to break the rules with probability [1.]
Agent 17 is not relatively desperate with income rank 0.21739130434782608
Agent 17 chose to break the rules with probability [1.]
Agent 18 is not relatively desperate with income rank 0.0
Agent 18 chose to break the rules with probability [0.99794351]
Agent 19 is not relatively desperate with income rank 0.43478260869565216
Agent 19 chose to break the rules with probability [1.]
Agent 20 is not relatively desperate with income rank 0.782608695652174
Agent 20 chose to break the rules with probability [1.]
Agent 21 is not relatively desperate with income rank 0.4782608695652174
Agent 21 chose to break the rules with probability [1.]
Agent 22 is not relatively desperate with income rank 0.17391304347826086
Agent 22 chose to break the rules with probability [1.]
Agent 23 is not relatively desperate with income rank 0.43478260869565216
Agent 23 chose to break the rules with probability [1.]
Agent 24 is not relatively desperate with income rank 0.21739130434782608
Agent 24 chose to break the rules with probability [1.]
Agent 25 is not relatively desperate with income rank 0.17391304347826086
Agent 25 chose to break the rules with probability [1.]
Agent 1 is not relatively desperate with income rank 0.043478260869565216
Agent 1 chose to break the rules with probability [0.99999997]
Agent 2 is not relatively desperate with income rank 0.043478260869565216
Agent 2 chose to break the rules with probability [0.99999999]
Agent 3 is not relatively desperate with income rank 0.4782608695652174
Agent 3 chose to break the rules with probability [1.]
Agent 4 is not relatively desperate with income rank 0.4782608695652174

In [32]:
results_df = pd.DataFrame(results)

results_df.head(51)

,RunId,iteration,Step,gamma,reward_rb,reward_rf,cost_rb,min_start_wealth,p,beta,...,Proportion crime,AgentID,Wealth Start,Wealth End,income rank,desperate_state,Rule-breaking choice,Caught,SV_rule_break,SV_follow_rules
0,0,0,0,0.3,500,50,500,200,0.1,-0.97,...,0.00,1,[2670.9502381801353],[2670.9502381801353],0.000000,0,0,False,None,None
1,0,0,0,0.3,500,50,500,200,0.1,-0.97,...,0.00,2,[-158.38294602012093],[-158.38294602012093],0.000000,0,0,False,None,None
2,0,0,0,0.3,500,50,500,200,0.1,-0.97,...,0.00,3,[3616.2089807520074],[3616.2089807520074],0.000000,0,0,False,None,None
3,0,0,0,0.3,500,50,500,200,0.1,-0.97,...,0.00,4,[4645.84690641646],[4645.84690641646],0.000000,0,0,False,None,None
4,0,0,0,0.3,500,50,500,200,0.1,-0.97,...,0.00,5,[3666.3761786131454],[3666.3761786131454],0.000000,0,0,False,None,None
5,0,0,0,0.3,500,50,500,200,0.1,-0.97,...,0.00,6,[4772.980735185642],[4772.980735185642],0.000000,0,0,False,None,None
6,0,0,0,0.3,500,50,500,200,0.1,-0.97,...,0.00,7,[5545.422373994852],[5545.422373994852],0.000000,0,0,False,None,None
7,0,0,0,0.3,500,50,500,200,0.1,-0.97,...,0.00,8,[2650.513882250262],[2650.513882250262],0.000000,0,0,False,None,None
8,0,0,0,0.3,500,50,500,200,0.1,-0.97,...,0.00,9,[1353.8908446242376],[1353.8908446242376],0.000000,0,0,False,None,None
9,0,0,0,0.3,500,50,500,200,0.1,-0.97,...,0.00,10,[4723.5447652739485],[4723.5447652739485],0.000000,0,0,False,None,None
10,0,0,0,0.3,500,50,500,200,0.1,-0.97,...,0.00,11,[3705.728292806959],[3705.728292806959],0.000000,0,0,False,None,None
11,0,0,0,0.3,500,50,500,200,0.1,-0.97,...,0.00,12,[5437.975397587967],[5437.975397587967],0.000000,0,0,False,None,None
12,0,0,0,0.3,500,50,500,200,0.1,-0.97,...,0.00,13,[4097.408592018621],[4097.408592018621],0.000000,0,0,False,None,None
13,0,0,0,0.3,500,50,500,200,0.1,-0.97,...,0.00,14,[7180.872928255882],[7180.872928255882],0.000000,0,0,False,None,None
14,0,0,0,0.3,500,50,500,200,0.1,-0.97,...,0.00,15,[7010.4336042526775],[7010.4336042526775],0.000000,0,0,False,None,None
15,0,0,0,0.3,500,50,500,200,0.1,-0.97,...,0.00,16,[1638.0265117490117],[1638.0265117490117],0.000000,0,0,False,None,None
16,0,0,0,0.3,500,50,500,200,0.1,-0.97,...,0.00,17,[3650.797696020524],[3650.797696020524],0.000000,0,0,False,None,None
17,0,0,0,0.3,500,50,500,200,0.1,-0.97,...,0.00,18,[2807.4546239893175],[2807.4546239893175],0.000000,0,0,False,None,None
18,0,0,0,0.3,500,50,500,200,0.1,-0.97,...,0.00,19,[4616.186505681653],[4616.186505681653],0.000000,0,0,False,None,None
19,0,0,0,0.3,500,50,500,200,0.1,-0.97,...,0.00,20,[4199.574112229306],[4199.574112229306],0.000000,0,0,False,None,None
20,0,0,0,0.3,500,50,500,200,0.1,-0.97,...,0.00,21,[3691.120940451693],[3691.120940451693],0.000000,0,0,False,None,None
21,0,0,0,0.3,500,50,500,200,0.1,-0.97,...,0.00,22,[3641.955063475264],[3641.955063475264],0.000000,0,0,False,None,None
22,0,0,0,0.3,500,50,500,200,0.1,-0.97,...,0.00,23,[4646.550466389254],[4646.550466389254],0.000000,0,0,False,None,None
23,0,0,0,0.3,500,50,500,200,0.1,-0.97,...,0.00,24,[3972.8173252882284],[3972.8173252882284],0.000000,0,0,False,None,None
24,0,0,0,0.3,500,50,500,200,0.1,-0.97,...,0.00,25,[3715.7633574377624],[3715.7633574377624],0.000000,0,0,False,None,None
25,0,0,1,0.3,500,50,500,200,0.1,-0.97,...,0.96,1,[2670.9502381801353],[2670.9502381801353],0.391304,0,1,False,[10.131845685896579],[5.648476297674752]
26,0,0,1,0.3,500,50,500,200,0.1,-0.97,...,0.96,2,[-158.38294602012093],[-158.38294602012093],0.565217,0,1,False,[11.23529021630717],[5.9959565742397976]
27,0,0,1,0.3,500,50,500,200,0.1,-0.97,...,0.96,3,[3616.2089807520074],[3616.2089807520074],0.043478,0,1,False,[9.350860616971527],[5.340314213259836]
28,0,0,1,0.3,500,50,500,200,0.1,-0.97,...,0.96,4,[4645.84690641646],[4645.84690641646],0.130435,0,1,False,[9.768133412773965],[5.512138353105235]
29,0,0,1,0.3,500,50,500,200,0.1,-0.97,...,0.96,5,[3666.3761786131454],[3666.3761786131454],0.260870,0,1,False,[10.064743044529745],[5.624204879074551]
30,0,0,1,0.3,500,50,500,200,0.1,-0.97,...,0.96,6,[4772.980735185642],[4772.980735185642],0.434783,0,1,False,[11.78554996778153],[6.136152949982984]
31,0,0,1,0.3,500,50,500,200,0.1,-0.97,...,0.96,7,[5545.422373994852],[5545.422373994852],0.913043,0,1,False,[29.330507931861924],[8.380239180290577]
32,0,0,1,0.3,500,50,500,200,0.1,-0.97,...,0.96,8,[2650.513882250262],[2650.513882250262],0.173913,0,1,False,[9.834952042257774],[5.538081743008259]
33,0,0,1,0.3,500,50,500,200,0.1,-0.97,...,0.96,9,[1353.8908446242376],[1353.8908446242376],-0.043478,1,0,False,[-1201.1965971997533],[5.2649483144717575]
34,0,0,1,0.3,500,50,500,200,0.1,-0.97,...,0.96,10,[4723.5447652739485],[4723.5447652739485],0.347826,0,1,False,[10.938509349796997],[5.911569454264489]
35,0,0,1,0.3,500,50,500,200,0.1,-0.97,...,0.96,11,[3705.728292806959],[3705.728292806959],0.260870,0,1,False,[10.656969493703198],[5.825531064102996]
36,0,0,1,0.3,500,50,500,200,0.1,-0.97,...,0.96,12,[5437.975397587967],[5437.975397587967],0.869565,0,1,False,[28.455850368071857],[8.146775007947495]
37,0,0,1,0.3,500,50,500,200,0.1,-0.97,...,0.96,13,[4097.408592018621],[4097.408592018621],0.608696,0,1,False,[24.86216353950424],[7.278928038142754]
38,0,0,1,0.3,500,50,500,200,0.1,-0.97,...,0.96,14,[7180.872928255882],[7180.872928255882],1.000000,0,1,False,[38.07048972417609],[10.853657494902516]
39,0,0,1,0.3,500,50,500,200,0.1,-0.97,...,0.96,15,[7010.4336042526775],[7010.4336042526775],0.956522,0,1,False,[37.375670469471956],[10.653338522068942]
40,0,0,1,0.3,500,50,500,200,0.1,-0.97,...,0.96,16,[1638.0265117490117],[1638.0265117490117],0.043478,0,1,True,[9.656896274100209],[5.468015530855014]
41,0,0,1,0.3,500,50,500,200,0.1,-0.97,...,0.96,17,[3650.797696020524],[3650.797696020524],0.173913,0,1,True,[9.839026470811989],[5.539650320711911]
42,0,0,1,0.3,500,50,500,200,0.1,-0.97,...,0.96,18,[2807.4546239893175],[2807.4546239893175],0.304348,0,1,False,[12.466790729962106],[6.282093653140062]
43,0,0,1,0.3,500,50,500,200,0.1,-0.97,...,0.96,19,[4616.186505681653],[4616.186505681653],0.086957,0,1,False,[9.350548292083676],[5.34017895018482]
44,0,0,1,0.3,500,50,500,200,0.1,-0.97,...,0.96,20,[4199.574112229306],[4199.574112229306],0.739130,0,1,False,[26.137884463298874],[7.5641543302359135]
45,0,0,1,0.3,500,50,500,200,0.1,-0.97,...,0.96,21,[3691.120940451693],[3691.120940451693],0.173913,0,1,False,[10.432913622990592],[5.752710433856816]
46,0,0,1,0.3,500,50,500,200,0.1,-0.97,...,0.96,22,[3641.955063475264],[3641.955063475264],0.086957,0,1,True,[9.712664975232622],[5.490283916892954]
47,0,0,1,0.3,500,50,500,200,0.1,-0.97,...,0.96,23,[4646.550466389254],[4646.550466389254],0.130435,0,1,False,[9.77818505139221],[5.516067645158858]
48,0,0,1,0.3,500,50,500,200,0.1,-0.97,...,0.96,24,[3972.8173252882284],[3972.8173252882284],0.173913,0,1,False,[22.684611636734267],[6.891411853000398]
49,0,0,1,0.3,500,50,500,200,0.1,-0.97,...,0.96,25,[3715.7633574377624],[3715.7633574377624],0.130435,0,1,False,[10.814326466795585],[5.87435324476715]
50,0,0,2,0.3,500,50,500,200,0.1,-0.97,...,1.00,1,[2670.9502381801353],[2670.9502381801353],0.391304,0,1,False,[24.48036284810598],[7.200648094792784]

In [181]:
# Save the results to a CSV file
results_df.to_csv("relative_desp_results.csv", index=False)

In [ ]:
# Get rid of the rows where "Step" is 0
results_df = results_df[results_df["Step"] > 0]

## Data Visualization

In [ ]:
# Calculate the Gini coefficient for the population
def gini_coefficient(wealths):
    """Calculate the Gini coefficient of a list of wealth values."""
    n = len(wealths)
    if n == 0:
        return 0
    sorted_wealths = np.sort(wealths)
    cumulative_wealths = np.cumsum(sorted_wealths)
    total_wealth = cumulative_wealths[-1]
    if total_wealth == 0:
        return 0
    gini_index = (2 * np.sum((np.arange(1, n + 1) * sorted_wealths))) / (n * total_wealth) - (n + 1) / n
    return gini_index
gini = gini_coefficient(results_df["Wealth End"])
print(f"Gini Coefficient: {gini}")

In [ ]:
# Show distribution of wealth at the end of the simulation
plt.figure(figsize=(10, 6))
sns.histplot(results_df["Wealth End"], bins=30, kde=True)
plt.title("Distribution of Wealth at the End of Simulation")
plt.xlabel("Wealth End")
plt.ylabel("Frequency")
plt.show()

In [ ]:
# Show relationship between wealth and rule-breaking behavior
plt.figure(figsize=(10, 6))
sns.scatterplot(x="Wealth End", y="Rule-breaking choice", data=results_df, alpha=0.5)
plt.title("Wealth vs. Rule-breaking Behavior")

In [ ]:
# Show the relationship between income rank and rule-breaking behavior
plt.figure(figsize=(10, 6))
sns.scatterplot(x="income rank", y="Rule-breaking choice", data=results_df, alpha=0.5)
plt.title("Income Rank vs. Rule-breaking Behavior")
plt.xlabel("Income Rank")
plt.ylabel("Rule-breaking choice")

In [ ]:
# Show the relationship between income rank and the expected utility of rule-breaking and following rules
plt.figure(figsize=(10, 6))
sns.scatterplot(x="income rank", y="SV_rule_break", data=results_df, alpha=0.5, label="Expected Utility of Rule Breaking")
sns.scatterplot(x="income rank", y="SV_follow_rules", data=results_df, alpha=0.5, label="Expected Utility of Following Rules")
plt.title("Income Rank vs. Expected Utility of Rule-breaking and Following Rules")
plt.xlabel("Income Rank")
plt.ylabel("Expected Utility")
plt.legend()
plt.show()

### Grid Visualization